export const DUMMY_DATA = [
    {
        Title: "Mission Mangal",
        Year: "2019",
        imdbID: "tt9248972",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BZThmMWFlOWYtY2M0YS00OWIxLWI4MzgtYTJhMDNkZDY4ZjhjXkEyXkFqcGdeQXVyNzc4NzEzNjY@._V1_SX300.jpg",
    },
    {
        Title: "Mission: Impossible",
        Year: "1966–1973",
        imdbID: "tt0060009",
        Type: "series",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTg3MDQ4ODQwNF5BMl5BanBnXkFtZTcwODMwODM0MQ@@._V1_SX300.jpg",
    },
    {
        Title: "Torrente 2: Mission in Marbella",
        Year: "2001",
        imdbID: "tt0257231",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTY4MzAyMTY4MV5BMl5BanBnXkFtZTgwMjU5NDI1MDE@._V1_SX300.jpg",
    },
    {
        Title: "Mission Kashmir",
        Year: "2000",
        imdbID: "tt0248185",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzdhY2JjMjctMGE1Mi00MjMyLWI1OTAtYTJlMjBhYWU0OWRiXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg",
    },
    {
        Title: "Mission London",
        Year: "2010",
        imdbID: "tt1127702",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTQ3MjIzMDU1M15BMl5BanBnXkFtZTcwNTQ3Mjk0Mw@@._V1_SX300.jpg",
    },
    {
        Title: "Dug's Special Mission",
        Year: "2009",
        imdbID: "tt1537759",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTQ3NjI1MjQyNl5BMl5BanBnXkFtZTgwMTkyMDgwMjE@._V1_SX300.jpg",
    },
    {
        Title: "The Last Deadly Mission",
        Year: "2008",
        imdbID: "tt0920470",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzlmZWI0NGQtOGUzZC00YjBmLTgyMDYtYTY4NThiMzY1YTk4XkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg",
    },
    {
        Title: "The Mission",
        Year: "1999",
        imdbID: "tt0220644",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzUxNWJjZTktZGY0Ni00ZGZlLTgzOTUtODljMjJiZWU2ZjkzXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    },
    {
        Title: "Mission Hill",
        Year: "1999–2002",
        imdbID: "tt0197148",
        Type: "series",
        Poster: "https://m.media-amazon.com/images/M/MV5BYTFiYmRhMGUtYzc5ZC00ZGU2LTkxNDEtNTQwZWU0NDk3MTQzXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    },
    {
        Title: "Mission of Honor",
        Year: "2018",
        imdbID: "tt7515456",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BMDQ0ZTg0NDgtNGNlMy00MjQ4LTk2ZWItODhmZjQzZmI0MmRhXkEyXkFqcGdeQXVyODY4ODQ0ODI@._V1_SX300.jpg",
    },
];
